### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by leoheck** [kreso-t/cncjs-kt-ext#11]
Hi, I am trying to install it on a Raspberry Pi 3. 

I'm following your instructions to install it but I am receiving this:
![image](https://user-images.githubusercontent.com/1277920/71447266-22c9de80-270b-11ea-8346-8fff32e69411.png)

Do you have any idea what I am doing wrong?

**Comment by leoheck** [comment]
I am also looking at the help and I have some issues.

The `-s, --secret` parameter does not show a `<value>` filed next to it like in `port` flag, for example.  Is it right? Also, some parameters like `-c, --config <filename>` show that the default is `~/.cncrc` but also show `(default: "")` at the end of the string. Is it right?

```
➜  cncjs-kt-ext git:(master) node . --help
Usage: cncjs-kt-ext -s <secret> -p <port> [options]

Options:
  -V, --version                       output the version number
  -s, --secret                        the secret key stored in the ~/.cncrc file
  -p, --port <port>                   path or name of serial port (default: "")
  -b, --baudrate <baudrate>           baud rate (default: 115200) (default: 0)
  -c, --config <filename>             set the config file (deafult: ~/.cncrc) (default: "")
  --socket-address <address>          socket address or hostname (default: localhost) (default: "")
  --socket-port <port>                socket port (default: 8000) (default: "")
  --controller-type <type>            controller type: Grbl|Smoothie|TinyG (default: Grbl) (default: "")
  --access-token-lifetime <lifetime>  access token lifetime in seconds or a time span string (default: 30d) (default: "")
  -h, --help                          output usage information
```

**Comment by leoheck** [comment]
Also, the `-s, --secret` does not work

![image](https://user-images.githubusercontent.com/1277920/71447389-9b7d6a80-270c-11ea-99cc-20865320daca.png)

**Comment by leoheck** [comment]
I figured out that I can use the `CNCJS_SECRET` environment variable. So now, I am receiving the following output:

```
Connection error. Unauthorized user: user.id=, user.name=cncjs-autolevel
```

How do I set these user.id and user.name?

**Comment by leoheck** [comment]
Alright, I was able to run it by adding my credentials directly on the `id` and `name` fields on `generateAccessToken` function.

**Comment by matthgyver** [comment]
Thank's guy !
Little precision : ID could be found in the ``~/.cncrc`` file

**Comment by leoheck** [comment]
@matthgyver Yeap that is right. I am fixing these things on my fork. I was not able to test it yet. I just know that it is running. If I can fix these command-line issues I will make a pull request here.
