### ISSUE TITLE
Autolevel ignores G20/G21

### ISSUE THREAD

**Issue by fughilli** [kreso-t/cncjs-kt-ext#25]
The autolevel plugin ignores G20/G21 commands, assuming that the input GCode is in mm. I ran output from FlatCAM in inches and caused a machine crash because the offsets were applied assuming mm but machine movement ended up being 25.4x (causing the engraving bit I was using to explode in spectacular fashion).

**Comment by fughilli** [comment]
Opened PR #26

**Comment by LongLiveCHIEF** [comment]
:+1: for exploding in spectacular fashion.  Suggest that you put that exact phrase into a commit so you can tell your grandkids you once had to write code to prevent things from exploding in spectacular fashion.
