### ISSUE TITLE
Weird serial port logs and UI lockup

### ISSUE THREAD

**Issue by erkkah** [kreso-t/cncjs-kt-ext#33]
Hi!
I'm trying to use the current repo version with cncjs 1.9.22, but I cannot get it to work.
When kt-ext connects to the serial port it spits out:
```
/dev/ttyUSB0: line 1: $'\r': command not found
/dev/ttyUSB0: line 2: Grbl: command not found
/dev/ttyUSB0: line 3: [MSG:$H: command not found
/dev/ttyUSB0: line 3: $X: command not found
...
```
As if its trying to interpret or run the output from the serial port, when this happens, the cncjs UI locks up as if it does not have contact with grbl anymore.

**Comment by kreso-t** [comment]
closing this, it's old
