### ISSUE TITLE
.cncrc file missing on pi

### ISSUE THREAD

**Issue by fc3sbob** [kreso-t/cncjs-kt-ext#43]
After installing cncjs with the PM2 method listed on their site, And the PM2 install for this extension I can't get the macro's to do anything.
, After setting the work space to 0,0,0 I send the macro to the serial console and the serial console responds with OK.
pm2 list shows that it was active along side of cncjs. It may have been working at this point but the issue was with me somehow.

I reinstalled using the raspberry pi script found on cncjs github and that method seems to use NPM to install. So I used that method to install this extension but it fails because the .cncrc file is missing from the home directory. Looking around I believe I found it in /cncjs/cncrc.cfg, I made a copy of it and moved it to /home/pi/.cncrc, but after running the "node . --port /dev/ttyACM0" command but it seems to hang and I have to ctrl+c to get out.

Also I tried to manually input the data in the string with the correct --id, --name, --secret, --port, --baudrate, --socket-address, --socket-port as I found in another issue report and got this.

`pi@cnccontroller:~ $ node . --id '40000205-fa31-4a6f-b692-e9830da19e5e' --name 'Bob' --secret '$2a$10$pfq4X0aZhxXnAN8Y1dWKOu' --port '/dev/ttyAMA0' --baudrate 115200 --socket-address 'localhost' --socket-port 80
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/pi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
pi@cnccontroller:~ $
`

The install script is a way better option in my opinion to get up and running fast and much easier for most people. Is there a way to get this extension running when installed that way?
I also tried older versions of cncjs just in case the .cncrc file was moved in the newest version but it's the same.

**Comment by Di3mex** [comment]
Have you been able to resolve this issue?
