### ISSUE TITLE
Unable to connect to CNCJS on Raspberry Pi

### ISSUE THREAD

**Issue by justincdotme** [kreso-t/cncjs-kt-ext#44]
I have cncjs installed on a Raspberry Pi. Cncjs is running on port 8000. I am unable to connect to it from this extension. The command that I am using is `node . -i "3577d143-82a2-4ad9-8f37-17d3e783d735" -n "justin" -s "REDACTED"`. I copied the value of the `-s` argument from the `secret` property of the `~/.cncrc` file that is on the Pi. 

The error that I get is :
```
Connection error. {
  message: 'invalid signature',
  code: 'invalid_token',
  type: 'UnauthorizedError'
}
```

I have tried replacing the `-s` value with the password that I use to log in to the cncjs UI. I have also tried using the hash value for `users.password` from `~/.cncrc`. I've tried passing these values with and without quotes, but the error message is the same. 

I'd really appreciate it if one of you could explain what I am doing wrong.

**Comment by Di3mex** [comment]
I have gotten passed this by setting 

"allowRemoteAccess": true,

in the cncrc.cfg file. But now I getting the next error described in https://github.com/kreso-t/cncjs-kt-ext/issues/43
