### ISSUE TITLE
odd compensations

### ISSUE THREAD

**Issue by alnonl** [kreso-t/cncjs-kt-ext#48]
Generally compensation is working, but seeing some incorrect conversions:

Codes without explicit X, Y converted to XNaN, YNaN
Source: G00 Z15.0000  --> Compensated: G00 XNaN YNaN Z15.003 ; Z15.000

Negative X,Y coordinates being mapped to positive equivalents
Source: G01 X-0.0743 Y20.3199 --> Compensated: G00 X0.0743 Y20.3199 Z15.003 ; Z15.000

**Comment by kreso-t** [comment]
reverted last pull request probably causing these problems
