### ISSUE TITLE
Just response "OK" after running macro

### ISSUE THREAD

**Issue by ehansen2580** [kreso-t/cncjs-kt-ext#67]
Installed yesterday through cloning.
Pasted the command into a macro and run it when my tool has been zeroed to 0,0,0
This is all I get
feeder> (#autolevel)
ok

I have an account set up on cncjs and that didn't make a difference.

**Comment by Ikswoknib** [comment]
Got it to work, I had to change the port to 80 instead of 8000, just startet the server with "node . --port /dev/ttyUSB0 --socket-port 80" then it worked for me.
