### ISSUE TITLE
Error starting the plugin.

### ISSUE THREAD

**Issue by dmdamen** [kreso-t/cncjs-kt-ext#9]
Hi, I had it working in the past but when I tried to start the plugin today I got an error.

![error_cncjs](https://user-images.githubusercontent.com/17194697/69872425-a2ec5800-12b5-11ea-8efa-761af320ac56.png)

**Comment by dmdamen** [comment]
[debug.log](https://github.com/kreso-t/cncjs-kt-ext/files/3905376/debug.log)
Here the debug log by the way.

**Comment by kreso-t** [comment]
Hi,

can you try to start it by using :
`
node . --port "/dev/ttyUSB0"
`

as "npm start" command seem to remove parameters starting with "-"

**Comment by dmdamen** [comment]
Works. Thanks a lot.
